# Generated by Django 6.0.6 on 2026-06-09 21:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(max_length=100)),
                ('severity', models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=20)),
                ('message', models.TextField()),
                ('resolved', models.BooleanField(default=False)),
                ('category', models.CharField(default='Inventory', max_length=50)),
                ('time_label', models.CharField(default='Just now', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=100, unique=True)),
                ('product_name', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=100)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('reorder_point', models.IntegerField(default=0)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('safety_stock', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('healthy', 'Healthy'), ('low', 'Low Stock'), ('overstocked', 'Overstocked'), ('critical', 'Critical')], default='healthy', max_length=20)),
                ('supplier', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=50)),
                ('lead_time_days', models.IntegerField(default=7)),
                ('reliability_score', models.DecimalField(decimal_places=2, default=100.0, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_available', models.IntegerField(default=0)),
                ('warehouse_location', models.CharField(default='Warehouse A', max_length=100)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_records', to='api.product')),
            ],
            options={
                'verbose_name_plural': 'Inventory Records',
            },
        ),
        migrations.CreateModel(
            name='CompetitorData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competitor_name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('availability', models.CharField(default='In Stock', max_length=50)),
                ('captured_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competitor_observations', to='api.product')),
            ],
            options={
                'verbose_name_plural': 'Competitor Observations',
            },
        ),
        migrations.CreateModel(
            name='AIRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommendation_type', models.CharField(choices=[('price', 'Pricing Optimization'), ('restock', 'Restock Replenishment'), ('supplier', 'Supplier Diversification')], max_length=20)),
                ('recommendation_text', models.TextField()),
                ('confidence_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('overridden', 'Overridden')], default='pending', max_length=20)),
                ('override_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('override_margin', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('override_impact', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ai_recommendations', to='api.product')),
            ],
        ),
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_sold', models.IntegerField()),
                ('selling_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('transaction_date', models.DateTimeField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_records', to='api.product')),
            ],
            options={
                'verbose_name_plural': 'Sales Transactions',
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('po_number', models.CharField(max_length=50, unique=True)),
                ('qty', models.IntegerField()),
                ('cost', models.DecimalField(decimal_places=2, max_digits=12)),
                ('order_date', models.DateField(auto_now_add=True)),
                ('expected_delivery', models.DateField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('ignored', 'Ignored'), ('in-transit', 'In Transit'), ('delayed', 'Delayed'), ('delivered', 'Delivered')], default='pending', max_length=20)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_orders', to='api.product')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_orders', to='api.supplier')),
            ],
        ),
    ]
